-- MySQL Script generated by MySQL Workbench
-- seg 21 jan 2019 15:46:12 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_usuario_cadastrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_usuario_cadastrado` (
  `id_usuario_cadastrado` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `excluir` TINYINT(1) NULL,
  `editar` TINYINT(1) NULL,
  `criar` TINYINT(1) NULL,
  PRIMARY KEY (`id_usuario_cadastrado`),
  UNIQUE INDEX `id_usuario_cadastrado_UNIQUE` (`id_usuario_cadastrado` ASC),
  INDEX `fk_tbl_usuario_cadastrado_tbl_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tbl_usuario_cadastrado_tbl_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`tbl_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_fazenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_fazenda` (
  `id_fazenda` INT NOT NULL,
  `nome_fazenda` VARCHAR(45) NOT NULL,
  `tamanho` DECIMAL(10,2) NOT NULL,
  `tbl_usuario_cadastrado_id_usuario_cadastrado` INT NOT NULL,
  PRIMARY KEY (`id_fazenda`),
  INDEX `fk_tbl_fazenda_tbl_usuario_cadastrado1_idx` (`tbl_usuario_cadastrado_id_usuario_cadastrado` ASC),
  CONSTRAINT `fk_tbl_fazenda_tbl_usuario_cadastrado1`
    FOREIGN KEY (`tbl_usuario_cadastrado_id_usuario_cadastrado`)
    REFERENCES `mydb`.`tbl_usuario_cadastrado` (`id_usuario_cadastrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tbl_fazenda_id_fazenda` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  INDEX `fk_tbl_usuario_tbl_fazenda1_idx` (`tbl_fazenda_id_fazenda` ASC),
  CONSTRAINT `fk_tbl_usuario_tbl_fazenda1`
    FOREIGN KEY (`tbl_fazenda_id_fazenda`)
    REFERENCES `mydb`.`tbl_fazenda` (`id_fazenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_animal_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_animal_tipo` (
  `id_animal_tipo` INT NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_animal_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_animal` (
  `id_animal` INT NOT NULL,
  `id_animal_pai` INT NOT NULL,
  `id_animal_mae` INT NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `data_nascimento` DATE NULL,
  `macho` TINYINT(1) NULL,
  `ovino` TINYINT(1) NULL,
  `tbl_animal_tipo_id_animal_tipo` INT NOT NULL,
  `tbl_fazenda_id_fazenda` INT NOT NULL,
  PRIMARY KEY (`id_animal`),
  UNIQUE INDEX `id_animal_UNIQUE` (`id_animal` ASC),
  INDEX `fk_tbl_animal_tbl_animal_tipo1_idx` (`tbl_animal_tipo_id_animal_tipo` ASC),
  INDEX `fk_tbl_animal_tbl_fazenda1_idx` (`tbl_fazenda_id_fazenda` ASC),
  CONSTRAINT `fk_tbl_animal_tbl_animal_tipo1`
    FOREIGN KEY (`tbl_animal_tipo_id_animal_tipo`)
    REFERENCES `mydb`.`tbl_animal_tipo` (`id_animal_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_animal_tbl_fazenda1`
    FOREIGN KEY (`tbl_fazenda_id_fazenda`)
    REFERENCES `mydb`.`tbl_fazenda` (`id_fazenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_pesagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_pesagem` (
  `id_pesagem` INT NOT NULL,
  `tbl_animal_id_animal` INT NOT NULL,
  `ecc` TINYINT NOT NULL,
  `data_pesagem` DATE NOT NULL,
  `famacha` TINYINT NOT NULL,
  `peso` DECIMAL NOT NULL,
  PRIMARY KEY (`id_pesagem`),
  UNIQUE INDEX `id_pesagem_UNIQUE` (`id_pesagem` ASC),
  INDEX `fk_tbl_pesagem_tbl_animal1_idx` (`tbl_animal_id_animal` ASC),
  CONSTRAINT `fk_tbl_pesagem_tbl_animal1`
    FOREIGN KEY (`tbl_animal_id_animal`)
    REFERENCES `mydb`.`tbl_animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_ocorrencia_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_ocorrencia_tipo` (
  `id_ocorrencia_tipo` INT NOT NULL,
  `ocorrencia_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ocorrencia_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_ocorrencia` (
  `id_ocorrencia` INT NOT NULL,
  `tbl_animal_id_animal` INT NOT NULL,
  `tbl_animal_id_animal_reprodutor` INT NOT NULL,
  `tbl_ocorrencia_tipo_id_ocorrencia_tipo` INT NOT NULL,
  `data_ocorrencia` DATE NOT NULL,
  `inseminada` TINYINT(1) NOT NULL,
  `observacao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_ocorrencia`),
  INDEX `fk_tbl_ocorrencia_tbl_ocorrencia_tipo1_idx` (`tbl_ocorrencia_tipo_id_ocorrencia_tipo` ASC),
  INDEX `fk_tbl_ocorrencia_tbl_animal1_idx` (`tbl_animal_id_animal` ASC),
  INDEX `fk_tbl_ocorrencia_tbl_animal2_idx` (`tbl_animal_id_animal_reprodutor` ASC),
  CONSTRAINT `fk_tbl_ocorrencia_tbl_ocorrencia_tipo1`
    FOREIGN KEY (`tbl_ocorrencia_tipo_id_ocorrencia_tipo`)
    REFERENCES `mydb`.`tbl_ocorrencia_tipo` (`id_ocorrencia_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_ocorrencia_tbl_animal1`
    FOREIGN KEY (`tbl_animal_id_animal`)
    REFERENCES `mydb`.`tbl_animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_ocorrencia_tbl_animal2`
    FOREIGN KEY (`tbl_animal_id_animal_reprodutor`)
    REFERENCES `mydb`.`tbl_animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_gestacao_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_gestacao_status` (
  `id_gestacao_status` INT NOT NULL,
  `gestacao_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gestacao_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_gestacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_gestacao` (
  `id_gestacao` INT NOT NULL,
  `tbl_gestacao_status_id_gestacao_status` INT NOT NULL,
  `tbl_animal_id_animal` INT NOT NULL,
  PRIMARY KEY (`id_gestacao`),
  INDEX `fk_tbl_gestacao_tbl_gestacao_status1_idx` (`tbl_gestacao_status_id_gestacao_status` ASC),
  INDEX `fk_tbl_gestacao_tbl_animal1_idx` (`tbl_animal_id_animal` ASC),
  CONSTRAINT `fk_tbl_gestacao_tbl_gestacao_status1`
    FOREIGN KEY (`tbl_gestacao_status_id_gestacao_status`)
    REFERENCES `mydb`.`tbl_gestacao_status` (`id_gestacao_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_gestacao_tbl_animal1`
    FOREIGN KEY (`tbl_animal_id_animal`)
    REFERENCES `mydb`.`tbl_animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
